name=input("请输入姓名")
# print("提示：您输入了数据：",name)
age=input("请输入年龄")
# print("提示：您输入了数据：",age)
sex=input("请输入性别")
# print("提示：您输入了数据：",sex)
birthdate=input("请输入生日")
# print("提示：您输入了数据：",birthdate)
email=input("请输入邮箱")
# print("提示：您输入了数据：",email)
phonenomber=input("请输入手机号")
# print("提示：您输入了数据：",phonenomber)